# Generated by Django 3.1.2 on 2021-03-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
