# Generated by Django 3.1.2 on 2021-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210315_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upvotes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
