# Generated by Django 3.1.2 on 2021-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210315_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='twiter_url',
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
