# Generated by Django 3.1.2 on 2021-03-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210315_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
