# Generated by Django 3.1.2 on 2021-03-15 21:51

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210315_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caption',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='launch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('S', 'Private'), ('P', 'Public'), ('I', 'In_progress')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'IT and Software'), (2, 'Design'), (3, 'Personal Development'), (4, 'Marketing'), (5, 'Music'), (6, 'Cloud')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='upvotes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
