# Generated by Django 3.1.2 on 2021-03-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210315_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
