# Generated by Django 3.1.2 on 2021-03-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210315_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
