# Generated by Django 3.1.2 on 2021-03-15 22:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210315_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'IT and Software'), (2, 'Design'), (3, 'Personal Development'), (4, 'Marketing'), (5, 'Music'), (6, 'Cloud')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
