# Generated by Django 3.1.2 on 2021-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
