# Generated by Django 3.1.2 on 2021-03-16 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_auto_20210316_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='product',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
